### PR TITLE
Allow parameter time dependence

### LINKED ISSUE #92: Pass parameter time-dependence functions
This issue is related to #76 and is to request that users should be able to pass time-dependence functions to `epidemic_*()`. 

These functions should be allowed to take the arguments `time` and `x` for a single parameter value, such as the transmission rate $\beta$; a pseudo-code example is shown below.

```r
epidemic_x(
  ...,
  time_dependence = list(
    beta = function(t, x, tmax = 365) x * sinpi(t / 365)
  )
)
```

A simple working example of the concept is below.

```r
mod_beta = function(time, x, tmax = 20) {
  x * scales::rescale(1 + sinpi(time / tmax), to = c(0, 1), from = c(0, 2))
}

# Define the SIR model function
sir_model <- function(time, state, parameters) {
  beta_now = parameters$fn(time, parameters$beta)
  
  dS <- -beta_now * state["S"] * state["I"] / parameters$N
  dI <- beta_now * state["S"] * state["I"] / parameters$N - parameters$gamma * state["I"]
  dR <- parameters$gamma * state["I"]
  
  return(list(c(dS, dI, dR)))
}

# Set initial conditions and parameters
initial_state <- c(S = 0.99, I = 0.01, R = 0)
parameters <- list(beta = 0.3, gamma = 0.1, N = 1, fn = mod_beta)

# Set time points for simulation
times <- seq(0, 100, by = 1)

# Solve the ODE using the ode solver from deSolve
sir_solution <- deSolve::ode(y = initial_state, times = times, func = sir_model, parms = parameters)

# Convert the solution to a data frame for plotting
solution_df <- as.data.frame(sir_solution)

library(ggplot2)

ggplot(solution_df, aes(time, I)) +
  geom_point()
```

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This PR is fixes #92, by allowing users to pass a list of functions to epidemic models that specify how model rate parameters vary over time. This is implemented in both R-only and Rcpp. The R-only version mirrors the Rcpp version and hence does not use {deSolve} events.

A good place to get started with reviewing is the vignette on time dependence.

See also #76.

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
Example after running the code (not a reprex):

```r
epidemic_default_cpp(
  population = uk_population,
  infection = pandemic,
  vaccination = vax_regime,
  time_dependence = list(
    beta = mod_beta
  ),
  time_end = 365, increment = 1
)
```

Rplot_vaccination

**Comment by pratikunterwegs** [comment]
Merging this PR today.

**Comment by adamkucharski** [comment]
Thanks for putting together, this looks very useful – no major comments for this version from a quick review of the vignette.

One thing that would be useful consider for next version is how to convert temporal data (e.g. vaccine coverage over time) into a continuous function for easy incorporation into {epidemics}/ODE model – as this conversion is often one of the more time-consuming pre-processing tasks when dealing with temporal interventions. {odin} has some useful interpolation functions we may want to lean on if relevant (as it's on CRAN): https://mrc-ide.github.io/odin/articles/odin.html

**Comment by pratikunterwegs** [comment]
Thanks for taking a look, very helpful.

Passing data such as vaccine coverage and interpolating it is actually pretty relevant for the ebola model which currently doesn't have a vaccinated compartment, so passing vaccine coverage changes will be useful. Just off the top of my head I think this can already be done in an ad hoc way within the function passed to `time_dependence`, using `approx()` to interpolate data that are used in the function `f(t, x, data = data)`.

I'll convert the suggestion into an issue and perhaps we can address it on the development day, happy to have input.

**Pull request merged**
