### PR TITLE
Consolidate `**/.gitignore` files

### PR DESCRIPTION
**Pull request by chartgerink**
This PR merges the various `.gitignore` files in subfolders into the main `.gitignore` in the root directory of the repository. 

It confused me to find multiple `.gitignore` files spread around the repo. I figured I would open this PR to see whether this is helpful.

I tried finding out what reasons there might be for doing this, but given that these are subfolders are without their one git history (they are not [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) I did not see a reason to keep them separate. 

If there's a specific reason for this, I would love to learn about it. I'll leave it to the code owner to decide what to do and respect that decision 😊

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
Thanks @chartgerink - the separate files are autogenerated by {usethis}, and I trust their logic for where to note files to be ignored for the various use cases. Agreed they migh make it less clear why a particular file one expects to be tracked is not - so I don't mind unifying them if that's a common policy we choose to adopt. I think it's best to leave these files as they are for now though.

- `src/.gitignore` is created by `usethis::use_rcpp_eigen()`
- `vignettes/.gitignore` is created by `usethis::use_vignette()`
- `.github/.gitignore` is created by `usethis::use_github_action_*()`.

**Comment by pratikunterwegs** [comment]
Just as a note: I used to be in favour of submodules, and I know @joshwlambert has tried them too, but we don't use them in this project and I don't think there's a use case at the moment either.

**Comment by chartgerink** [comment]
Thanks for the clarification @pratikunterwegs 🙏 I was not aware that it's a `usethis` thing. Appreciate the feedback 😊 

I'll close this PR.

**Comment by chartgerink** [comment]
Thanks! I will read those posts - good tip.

There is no hard prescription as to whether multiple or single `.gitignore` is best practice [from git itself](https://git-scm.com/docs/gitignore#_examples). It might vary depending on the specific language and community culture around it. 

I only have come across it in the case of submodules myself. By induction, I would think it is best practice but there are too many unknowns for me to say that confidently :-) It seems however that the R community (especially `usethis`) seems to prefer this structure at the time.

**Pull request closed without merging**
